[book]
authors = ["Marc Zweiler"]
language = "en"
multilingual = false
src = "src"
title = "The Flint Wiki"

[preprocessor.toc]
collapsible = true
#command = "mdbook-toc"
#renderer = ["html"]

[preprocessor.katex]
